# Generated by Django 5.1.4 on 2024-12-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=20, unique=True)),
                ('identifier', models.CharField(max_length=20)),
                ('published_date', models.DateField()),
                ('last_modified_date', models.DateField()),
                ('status', models.CharField(choices=[('ANALYZED', 'Analyzed'), ('MODIFIED', 'Modified'), ('REJECTED', 'Rejected')], max_length=20)),
            ],
            options={
                'ordering': ['-last_modified_date'],
            },
        ),
    ]
